
    - name: Install dependencies
      apt: pkg={{ item }} update_cache=yes
      with_items:
      - build-essential
      - libssl-dev
      - libffi-dev
      - python
      - python-dev
      - python-pip
      - python-software-properties
      - python-gpgme
      - unzip
      become: yes

    - name: Create home directories
      file: path=~/{{ item }} state=directory
      with_items:
      - Installs

    - name: Install Ansible configuration management
      pip: name=ansible version=2.2.2.0
      become: yes

    - name: Download Terraform installation resource
      get_url: url=https://releases.hashicorp.com/terraform/0.9.1/terraform_0.9.1_linux_amd64.zip dest=~/Installs/terraform_0.9.1_linux_amd64.zip
      register: terraform_get_url_result
      until: terraform_get_url_result | succeeded
      retries: 3
      delay: 1

    - name: Unarchive Terraform
      unarchive: src=~/Installs/terraform_0.9.1_linux_amd64.zip remote_src=yes dest=/tmp

    - name: Install Terraform
      copy: src=/tmp/terraform dest=/usr/local/bin remote_src=yes mode=0755
      become: yes

    - name: Get Packer installer
      get_url: url=https://releases.hashicorp.com/packer/1.0.0/packer_1.0.0_linux_amd64.zip dest=~/Installs/packer_1.0.0_linux_amd64.zip
      register: packer_get_url_result
      until: packer_get_url_result | succeeded
      retries: 3
      delay: 1

    - name: Unarchive Packer
      unarchive: src=~/Installs/packer_1.0.0_linux_amd64.zip remote_src=yes dest=/tmp

    - name: Install packer
      copy: src=/tmp/packer dest=/usr/local/bin remote_src=yes mode=0755
      become: yes

    - name: Install awscli
      pip: name=awscli
      become: yes

    - name: Install AWS IDP requirements
      apt: pkg={{ item }}
      with_items:
      - libxml2-utils
      - jq
      become: yes

    - name: Install vim plugins
      git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.dest }}
      with_items:
      - {repo: "https://github.com/pearofducks/ansible-vim.git", dest: ansible-vim}
      - {repo: "https://github.com/hashivim/vim-terraform.git", dest: vim-terraform}
      - {repo: "https://github.com/rodjek/vim-puppet.git", dest: vim-puppet}
